"""add hsn_sac to products

Revision ID: 1cff539dc1bb
Revises: 7d1a6351ed5b
Create Date: 2025-12-18 15:43:50.992206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cff539dc1bb'
down_revision = '7d1a6351ed5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    import sqlalchemy as sa
    inspector = sa.inspect(conn)
    products_columns = [col['name'] for col in inspector.get_columns('products')]
    
    # Add hsn_sac
    if 'hsn_sac' not in products_columns:
        op.add_column('products', sa.Column('hsn_sac', sa.String(length=50), nullable=True, server_default='0'))
    
    # Add tax inclusive price fields if missing
    if 'cost_price_inc_tax' not in products_columns:
        op.add_column('products', sa.Column('cost_price_inc_tax', sa.Float(), server_default='0.0', nullable=True))
    
    if 'selling_price_inc_tax' not in products_columns:
        op.add_column('products', sa.Column('selling_price_inc_tax', sa.Float(), server_default='0.0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'selling_price_inc_tax')
    op.drop_column('products', 'cost_price_inc_tax')
    op.drop_column('products', 'hsn_sac')
    # ### end Alembic commands ###
