"""add_user_profiles_and_invoice_fields

Revision ID: 7d1a6351ed5b
Revises: b27d3d468196
Create Date: 2025-11-27 11:04:19.051318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1a6351ed5b'
down_revision = 'b27d3d468196'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: user_profiles table already exists, only adding sales order fields
    
    # Add invoice and billing fields to sales_orders
    op.add_column('sales_orders', sa.Column('billing_name', sa.String(length=255), nullable=True))
    op.add_column('sales_orders', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('sales_orders', sa.Column('billing_phone', sa.String(length=50), nullable=True))
    op.add_column('sales_orders', sa.Column('billing_street_address', sa.String(length=255), nullable=True))
    op.add_column('sales_orders', sa.Column('billing_city', sa.String(length=100), nullable=True))
    op.add_column('sales_orders', sa.Column('billing_state', sa.String(length=100), nullable=True))
    op.add_column('sales_orders', sa.Column('billing_postal_code', sa.String(length=20), nullable=True))
    op.add_column('sales_orders', sa.Column('billing_country', sa.String(length=100), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_company_name', sa.String(length=255), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_street_address', sa.String(length=255), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_city', sa.String(length=100), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_state', sa.String(length=100), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_postal_code', sa.String(length=20), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_country', sa.String(length=100), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_phone', sa.String(length=50), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_email', sa.String(length=255), nullable=True))
    op.add_column('sales_orders', sa.Column('seller_gstin', sa.String(length=50), nullable=True))
    op.add_column('sales_orders', sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales_orders', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales_orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('sales_orders', sa.Column('payment_reference', sa.String(length=100), nullable=True))
    op.add_column('sales_orders', sa.Column('terms_and_conditions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'terms_and_conditions')
    op.drop_column('sales_orders', 'payment_reference')
    op.drop_column('sales_orders', 'payment_method')
    op.drop_column('sales_orders', 'due_date')
    op.drop_column('sales_orders', 'invoice_date')
    op.drop_column('sales_orders', 'seller_gstin')
    op.drop_column('sales_orders', 'seller_email')
    op.drop_column('sales_orders', 'seller_phone')
    op.drop_column('sales_orders', 'seller_country')
    op.drop_column('sales_orders', 'seller_postal_code')
    op.drop_column('sales_orders', 'seller_state')
    op.drop_column('sales_orders', 'seller_city')
    op.drop_column('sales_orders', 'seller_street_address')
    op.drop_column('sales_orders', 'seller_company_name')
    op.drop_column('sales_orders', 'billing_country')
    op.drop_column('sales_orders', 'billing_postal_code')
    op.drop_column('sales_orders', 'billing_state')
    op.drop_column('sales_orders', 'billing_city')
    op.drop_column('sales_orders', 'billing_street_address')
    op.drop_column('sales_orders', 'billing_phone')
    op.drop_column('sales_orders', 'billing_email')
    op.drop_column('sales_orders', 'billing_name')
    # ### end Alembic commands ###
