"""add_user_profiles_and_invoice_fields

Revision ID: 7d1a6351ed5b
Revises: b27d3d468196
Create Date: 2025-11-27 11:04:19.051318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1a6351ed5b'
down_revision = 'b27d3d468196'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    import sqlalchemy as sa
    inspector = sa.inspect(conn)
    
    # Check existing columns in sales_orders table
    sales_orders_columns = [col['name'] for col in inspector.get_columns('sales_orders')]
    
    # List of columns to add to sales_orders
    columns_to_add = [
        ('billing_name', sa.String(length=255)),
        ('billing_email', sa.String(length=255)),
        ('billing_phone', sa.String(length=50)),
        ('billing_street_address', sa.String(length=255)),
        ('billing_city', sa.String(length=100)),
        ('billing_state', sa.String(length=100)),
        ('billing_postal_code', sa.String(length=20)),
        ('billing_country', sa.String(length=100)),
        ('seller_company_name', sa.String(length=255)),
        ('seller_street_address', sa.String(length=255)),
        ('seller_city', sa.String(length=100)),
        ('seller_state', sa.String(length=100)),
        ('seller_postal_code', sa.String(length=20)),
        ('seller_country', sa.String(length=100)),
        ('seller_phone', sa.String(length=50)),
        ('seller_email', sa.String(length=255)),
        ('seller_gstin', sa.String(length=50)),
        ('invoice_date', sa.DateTime(timezone=True)),
        ('due_date', sa.DateTime(timezone=True)),
        ('payment_method', sa.String(length=50)),
        ('payment_reference', sa.String(length=100)),
        ('terms_and_conditions', sa.Text())
    ]
    
    for col_name, col_type in columns_to_add:
        if col_name not in sales_orders_columns:
            op.add_column('sales_orders', sa.Column(col_name, col_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'terms_and_conditions')
    op.drop_column('sales_orders', 'payment_reference')
    op.drop_column('sales_orders', 'payment_method')
    op.drop_column('sales_orders', 'due_date')
    op.drop_column('sales_orders', 'invoice_date')
    op.drop_column('sales_orders', 'seller_gstin')
    op.drop_column('sales_orders', 'seller_email')
    op.drop_column('sales_orders', 'seller_phone')
    op.drop_column('sales_orders', 'seller_country')
    op.drop_column('sales_orders', 'seller_postal_code')
    op.drop_column('sales_orders', 'seller_state')
    op.drop_column('sales_orders', 'seller_city')
    op.drop_column('sales_orders', 'seller_street_address')
    op.drop_column('sales_orders', 'seller_company_name')
    op.drop_column('sales_orders', 'billing_country')
    op.drop_column('sales_orders', 'billing_postal_code')
    op.drop_column('sales_orders', 'billing_state')
    op.drop_column('sales_orders', 'billing_city')
    op.drop_column('sales_orders', 'billing_street_address')
    op.drop_column('sales_orders', 'billing_phone')
    op.drop_column('sales_orders', 'billing_email')
    op.drop_column('sales_orders', 'billing_name')
    # ### end Alembic commands ###
